### ISSUE TITLE
Error when trying to delete no session

### ISSUE THREAD

**Issue by jenniferemshepherd** [Financial-Times/nori#71]
No session selected; Nori raises an error.

```TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.basename (path.js:1377:5)
    at promptOperation (/Users/jennifer.shepherd/.nvm/versions/node/v8.15.0/lib/node_modules/nori/src/interactive.js:152:58)
    at Object.exports.handler (/Users/jennifer.shepherd/.nvm/versions/node/v8.15.0/lib/node_modules/nori/src/interactive.js:185:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)```

**Comment by quarterto** [comment]
this doesn't seem to be happening any more 🙂
